### ISSUE TITLE
Locally linked node_modules breaks `tsconfig.json` resolution

### ISSUE THREAD

**Issue by o-alexandrov** [SukkaW/rollup-plugin-swc#55] opened 2023-11-14 07:19 UTC
The following issue happens when the package where `rollup-plugin-swc3` is locally linked.

```sh
Error: File './tsconfig.json' not found.
    at Be (/node_modules/get-tsconfig/dist/index.cjs:3:9201)
    at ie (/node_modules/get-tsconfig/dist/index.cjs:3:10245)
    at le (/node_modules/get-tsconfig/dist/index.cjs:3:10975)
    at Object.Le [as getTsconfig] (/node_modules/get-tsconfig/dist/index.cjs:3:11080)
    at p (/node_modules/rollup-plugin-swc3/dist/index.js:1:707)
    at Object.transform (/node_modules/rollup-plugin-swc3/dist/index.js:1:2016)
    at <anonymous> (/node_modules/rollup/dist/shared/rollup.js:1914:40) {
  code: 'PLUGIN_ERROR',
  plugin: 'swc',
  hook: 'transform',
  id: '/random-filename.ts',
  watchFiles: [...]
```

**Comment by SukkaW** [comment] 2023-11-14 08:28
Would you like to share more information?

From your issue, it appears that the `rollup-plugin-swc3` is somehow "linked", which may not be its intended usage. Providing a step-by-step reproduction of the problem would be much appreciated.

For the time being, I will close this issue. The issue would be reopened if further detail is provided.

**Closed as completed by SukkaW** 2023-11-14 08:28 UTC
