### ISSUE TITLE
Treating module as external dependency

### ISSUE THREAD

**Issue by goldenratio** [SukkaW/rollup-plugin-swc#31] opened 2023-02-15 10:52 UTC
Hey,
First of all, awesome work on this and thanks.

I am trying to move my current project from rollup-typescript2 to rollup-plugin-swc3

I treating some of the modules as external dependency, I don't want rollup to bundle them (https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency). This doesn't seem to work.

Minimal project Repos
rollup-typescript2: https://github.com/goldenratio/lerna-rollup2-rtp2-demo
rollup-plugin-swc3: https://github.com/goldenratio/lerna-rollup2-swc-demo

please build project using, npm run build,
Check the generated file, packages/sound/lib/sound.es.js

rtp2 generates, external imports properly
```
import { add } from '@lerna-demo/utils';

/**
 * PlayFX
 */
var playSFX = function () {
    console.log('playing sound sfx: ', add(4, 5));
};

export { playSFX };
//# sourceMappingURL=sound.es.js.map
```

But rollup-plugin-swc3, includes the extrernal code. Is it possible to keep it external?
```
/**
 * @param {number} x
 * @param {number} y
 * @returns {number}
 */ var add = function(x, y) {
    return x + y;
};

/**
 * PlayFX
 */ var playSFX = function() {
    console.log("playing sound sfx: ", add(4, 5));
};

export { playSFX };
//# sourceMappingURL=sound.es.js.map

```

**Comment by SukkaW** [comment] 2023-02-15 19:04
@goldenratio

```diff
// tsconfig.swc-loader.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
-    "paths": {
-      "@lerna-demo/*": ["./packages/*/src"]
-    }
  },
  "exclude": [
    "packages/*/sandbox-*/*",
    "packages/*/sandbox/*",
    "packages/*/__tests__/*",
    "packages/*/lib/*",
    "output/*",
    "preview/*"
  ]
}
```

This should help.

So, rollup-plugin-swc3 **will** try to read the provided `tsconfig` (in your case, you provided a filename `tsconfig.swc-loader.json`) and pass as many options as possible to swc, `baseUrl` and `paths` included.

**SWC will transform your import alias from absolute import into relative import based on the provided `baseUrl` and `paths` options.** So your imports...

```ts
import { add } from '@lerna-demo/utils';
```

...will be transformed into...

```ts
import { add } from '../../utils/src';
```

...by SWC, and that's why it is getting bundled by rollup (since the import paths are changed and it is no longer included in the `external`). `rollup-plugin-typescript2` (tsc) doesn't have this behavior (it won't change your import path based on `baseUrl` and `paths`), but it is SWC's expected behavior.

I am closing the issue for now. And if you have any questions, feel free to comment and I will try my best to help you out.

**Closed as completed by SukkaW** 2023-02-15 19:04 UTC

**Comment by goldenratio** [comment] 2023-02-15 19:22
@SukkaW thanks for the explanation, much appreciate it.
